const express = require('express')
const serveIndex = require('serve-index')
const app = express()
app.use(express.static(__dirname + '/question'))
app.use(serveIndex(__dirname + '/question'))
app.listen(4001)
console.log('Listening 4001.')
